# Generated by Django 5.2.4 on 2025-08-12 06:18

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedproduct',
            name='session',
        ),
        migrations.RemoveField(
            model_name='sharedproduct',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='shoppingsession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='shoppingsession',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shoppingsession',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.DeleteModel(
            name='SessionMessage',
        ),
        migrations.DeleteModel(
            name='SharedProduct',
        ),
    ]
