# # Generated by Django 5.2.4 on 2025-07-28 15:31

# import django.db.models.deletion
# from django.conf import settings
# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('accounts', '0002_userprofile'),
#     ]

#     operations = [
#         migrations.AddField(
#             model_name='account',
#             name='referral_code',
#             field=models.CharField(blank=True, max_length=100, unique=True),
#         ),
#         migrations.AddField(
#             model_name='account',
#             name='referred_by',
#             field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
#         ),
#     ]

# accounts/migrations/0003_account_referral_code_account_referred_by.py

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion
import uuid

def generate_referral_codes(apps, schema_editor):
    Account = apps.get_model('accounts', 'Account')
    used_codes = set()
    for user in Account.objects.all():
        code = str(uuid.uuid4()).replace('-', '')[:10]
        while code in used_codes:
            code = str(uuid.uuid4()).replace('-', '')[:10]
        user.referral_code = code
        used_codes.add(code)
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='referral_code',
            field=models.CharField(blank=True, max_length=100, null=True),  # No unique=True yet
        ),
        migrations.AddField(
            model_name='account',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(generate_referral_codes),  # Generate values first
        migrations.AlterField(
            model_name='account',
            name='referral_code',
            field=models.CharField(blank=True, max_length=100, unique=True, null=True),
        ),
    ]
