# Generated by Django 5.2.4 on 2025-07-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_referral_code_account_referred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='referral_code',
            field=models.CharField(blank=True, default='tempcode', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
