# Generated by Django 5.1.3 on 2025-11-27 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_last_login_alter_account_referral_code'),
        ('accounts', '0005_create_default_superuser'),
    ]

    operations = [
    ]
